import useLocalAxios from "@/hook/useAxios";
import styles from "@/styles/Home.module.css";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

interface Template {
  templating: string;
  users: { userId: string; firstName: string; lastName: string }[];
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const axios = useLocalAxios();

  const [template, setTemplate] = useState<Template | null>(null);

  const handleClick = async () => {
    try {
      const response = await axios.get("/template");
      setTemplate(response.data);
    } catch (e) {
      console.log(e);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <button onClick={handleClick}>click</button>

          {template && (
            <div>
              <div>{template.templating}</div>
              {template.users.map((user) => (
                <div key={user.userId}>
                  {user.firstName} {user.lastName}
                </div>
              ))}
            </div>
          )}
        </main>
      </div>
    </>
  );
}
